//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcFlashCalculator.Core.Locals {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArcFlashCalculator.Core.Locals.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  A.
        /// </summary>
        public static string A {
            get {
                return ResourceManager.GetString("A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: Voltage test.
        /// </summary>
        public static string Action_Example {
            get {
                return ResourceManager.GetString("Action_Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe the type of energized work that will be performed (example: troubleshooting, testing, verify de-energized)..
        /// </summary>
        public static string Action_Tooltip_Message {
            get {
                return ResourceManager.GetString("Action_Tooltip_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select equipment voltage type where work will be performed..
        /// </summary>
        public static string Alternating_Current_Tooltip_Message {
            get {
                return ResourceManager.GetString("Alternating_Current_Tooltip_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARC CALCULATOR RESULT.
        /// </summary>
        public static string ARC_Calculator_Result_Title {
            get {
                return ResourceManager.GetString("ARC_Calculator_Result_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arc Duration.
        /// </summary>
        public static string Arc_Duration {
            get {
                return ResourceManager.GetString("Arc_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: 0.5.
        /// </summary>
        public static string Arc_Duration_Example {
            get {
                return ResourceManager.GetString("Arc_Duration_Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arc Duration (seconds).
        /// </summary>
        public static string Arc_Duration_seconds {
            get {
                return ResourceManager.GetString("Arc_Duration_seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time for upstream protective device (located outside of the enclosure to be worked-on) to operate for the arcing fault current calculated. Consider equipment condition and  maintenance. If protective device clearing time is unknown:a) Enter 2 seconds; or b) Consult time current curve for the device; or c) Request support from Engineering Services. Valid range: 0.01 - 2.00.
        /// </summary>
        public static string Arc_Duration_Tooltip_Message {
            get {
                return ResourceManager.GetString("Arc_Duration_Tooltip_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} sec..
        /// </summary>
        public static string Arc_Duration_With_Unit {
            get {
                return ResourceManager.GetString("Arc_Duration_With_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arc Flash Boundary (feet).
        /// </summary>
        public static string Arc_Flash_Boundary_Feet {
            get {
                return ResourceManager.GetString("Arc_Flash_Boundary_Feet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arc Flash Boundary (inches).
        /// </summary>
        public static string Arc_Flash_Boundary_Inches {
            get {
                return ResourceManager.GetString("Arc_Flash_Boundary_Inches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arc Flash Estimate:.
        /// </summary>
        public static string Arc_Flash_Estimate {
            get {
                return ResourceManager.GetString("Arc_Flash_Estimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARC FLASH ESTIMATE REPORT.
        /// </summary>
        public static string ARC_FLASH_ESTIMATE_REPORT {
            get {
                return ResourceManager.GetString("ARC_FLASH_ESTIMATE_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at Working Distance:.
        /// </summary>
        public static string At_Working_Distance {
            get {
                return ResourceManager.GetString("At_Working_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery Enclosure?.
        /// </summary>
        public static string Battery_Enclosure {
            get {
                return ResourceManager.GetString("Battery_Enclosure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery String Voltage (volts).
        /// </summary>
        public static string Battery_String_Voltage {
            get {
                return ResourceManager.GetString("Battery_String_Voltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolted Fault Current (kA).
        /// </summary>
        public static string Bolted_Fault_Current {
            get {
                return ResourceManager.GetString("Bolted_Fault_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolted Fault Current (amps).
        /// </summary>
        public static string Bolted_Fault_Current_amps {
            get {
                return ResourceManager.GetString("Bolted_Fault_Current_amps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breaker Settings.
        /// </summary>
        public static string Breaker_Settings_Heading {
            get {
                return ResourceManager.GetString("Breaker_Settings_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breaker Style.
        /// </summary>
        public static string Breaker_Style {
            get {
                return ResourceManager.GetString("Breaker_Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cable.
        /// </summary>
        public static string Cable {
            get {
                return ResourceManager.GetString("Cable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  cal/cm².
        /// </summary>
        public static string CalCentimeterSquared {
            get {
                return ResourceManager.GetString("CalCentimeterSquared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        public static string Calculate {
            get {
                return ResourceManager.GetString("Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate Arc Duration.
        /// </summary>
        public static string Calculate_Arc_Duration_Button {
            get {
                return ResourceManager.GetString("Calculate_Arc_Duration_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this to calculate arc duration. A sensor rating must be provided for this calculation to work..
        /// </summary>
        public static string Calculate_Arc_Duration_Tooltip_Message {
            get {
                return ResourceManager.GetString("Calculate_Arc_Duration_Tooltip_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculated Arc Duration = {0}.
        /// </summary>
        public static string Calculated_Arc_Duration {
            get {
                return ResourceManager.GetString("Calculated_Arc_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a date..
        /// </summary>
        public static string Calculation_Date_Tooltip_Message {
            get {
                return ResourceManager.GetString("Calculation_Date_Tooltip_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation History.
        /// </summary>
        public static string Calculation_History {
            get {
                return ResourceManager.GetString("Calculation_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a calculation below. WARNING!! Your selection will delete downstream calculations!.
        /// </summary>
        public static string Calculation_History_Heading {
            get {
                return ResourceManager.GetString("Calculation_History_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation Name.
        /// </summary>
        public static string Calculation_Name {
            get {
                return ResourceManager.GetString("Calculation_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a name for this calculation..
        /// </summary>
        public static string Calculation_Name_Instructions {
            get {
                return ResourceManager.GetString("Calculation_Name_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CALCULATION PREVIEW.
        /// </summary>
        public static string Calculation_Preview_Heading {
            get {
                return ResourceManager.GetString("Calculation_Preview_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circuit (amps).
        /// </summary>
        public static string Circuit_Amps {
            get {
                return ResourceManager.GetString("Circuit_Amps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circuit  Diagram Preview:.
        /// </summary>
        public static string Circuit_Diagram_Heading {
            get {
                return ResourceManager.GetString("Circuit_Diagram_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clothing Description.
        /// </summary>
        public static string Clothing_Description {
            get {
                return ResourceManager.GetString("Clothing_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arc Flash Suit.
        /// </summary>
        public static string ClothingDescriptionDetails40PartA {
            get {
                return ResourceManager.GetString("ClothingDescriptionDetails40PartA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A total clothing system consisting of arc rated shirt and pants and/or arc-rated coveralls and/or arc flash coat and pants(clothing system minimum arc rating of 40).
        /// </summary>
        public static string ClothingDescriptionDetails40PartB {
            get {
                return ResourceManager.GetString("ClothingDescriptionDetails40PartB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arc-rated long-sleeve shirt with arc-rated pants (minimum arc rating of 8).
        /// </summary>
        public static string ClothingDescriptionDetails8PartA {
            get {
                return ResourceManager.GetString("ClothingDescriptionDetails8PartA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arc-rated coveralls(minimum arc rating of 8).
        /// </summary>
        public static string ClothingDescriptionDetails8PartB {
            get {
                return ResourceManager.GetString("ClothingDescriptionDetails8PartB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arc-rated FR shirt and FR pants or arc-rated FR coverall, and arc flash suit selected so that the system arc rating meets the minimum.
        /// </summary>
        public static string ClothingDescriptionDetailsOnePointTwo {
            get {
                return ResourceManager.GetString("ClothingDescriptionDetailsOnePointTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conductor?.
        /// </summary>
        public static string Conductor {
            get {
                return ResourceManager.GetString("Conductor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conductor.
        /// </summary>
        public static string Conductor_Heading {
            get {
                return ResourceManager.GetString("Conductor_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conductor Length (feet).
        /// </summary>
        public static string Conductor_Length {
            get {
                return ResourceManager.GetString("Conductor_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the cable length in feet..
        /// </summary>
        public static string Conductor_Length_Tooltip_Message {
            get {
                return ResourceManager.GetString("Conductor_Length_Tooltip_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: 12.
        /// </summary>
        public static string Conductor_Per_Phase_Example {
            get {
                return ResourceManager.GetString("Conductor_Per_Phase_Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If parallel conductors are used, enter the number of conductors..
        /// </summary>
        public static string Conductor_Per_Phase_Tooltip_Message {
            get {
                return ResourceManager.GetString("Conductor_Per_Phase_Tooltip_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conductor Size (kcmil/AWG).
        /// </summary>
        public static string Conductor_Size {
            get {
                return ResourceManager.GetString("Conductor_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose size of conductors or cable from transformer to equipment or from location where fault current is known to the equipment to be worked on. Conductor impedance is based on copper (CU)conductors.
        /// </summary>
        public static string Conductor_Size_Tooltip_Message {
            get {
                return ResourceManager.GetString("Conductor_Size_Tooltip_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Conductors per Phase.
        /// </summary>
        public static string Conductors_per_Phase {
            get {
                return ResourceManager.GetString("Conductors_per_Phase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} AWG.
        /// </summary>
        public static string ConductorSize {
            get {
                return ResourceManager.GetString("ConductorSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} conductor(s) per phase.
        /// </summary>
        public static string ConductorsPerPhase {
            get {
                return ResourceManager.GetString("ConductorsPerPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DANGER.
        /// </summary>
        public static string DANGER {
            get {
                return ResourceManager.GetString("DANGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DO NOT PROCEED! Use the button above to
        ///&quot;Find Safe Working Distance for Available PPE&quot;
        ///or contact your supervisor for instructions..
        /// </summary>
        public static string Danger_Summary {
            get {
                return ResourceManager.GetString("Danger_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Format.
        /// </summary>
        public static string Date_Format {
            get {
                return ResourceManager.GetString("Date_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Manufacturer.
        /// </summary>
        public static string Device_Manufacturer {
            get {
                return ResourceManager.GetString("Device_Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery Rack = Open Air .
        /// </summary>
        public static string Direct_Current_In_Cabinet_Tooltip_Message {
            get {
                return ResourceManager.GetString("Direct_Current_In_Cabinet_Tooltip_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery Cabinet = In Box.
        /// </summary>
        public static string Direct_Current_Open_Air_Tooltip_Message {
            get {
                return ResourceManager.GetString("Direct_Current_Open_Air_Tooltip_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select equipment voltage type where work will be performed..
        /// </summary>
        public static string Direct_Current_Tooltip_Message {
            get {
                return ResourceManager.GetString("Direct_Current_Tooltip_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DO NOT USE for actual calculations.
        /// </summary>
        public static string Do_Not_Use {
            get {
                return ResourceManager.GetString("Do_Not_Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Enclosure?.
        /// </summary>
        public static string Equipment_Enclosure {
            get {
                return ResourceManager.GetString("Equipment_Enclosure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Type.
        /// </summary>
        public static string Equipment_Type {
            get {
                return ResourceManager.GetString("Equipment_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the type of equipment where energized work will be performed..
        /// </summary>
        public static string Equipment_Type_Tooltip_Message {
            get {
                return ResourceManager.GetString("Equipment_Type_Tooltip_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Arc Current (kA).
        /// </summary>
        public static string Estimated_Arc_Current {
            get {
                return ResourceManager.GetString("Estimated_Arc_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Arc Fault Current (kA).
        /// </summary>
        public static string Estimated_Arc_Fault_Current {
            get {
                return ResourceManager.GetString("Estimated_Arc_Fault_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Arc Fault Current (amps).
        /// </summary>
        public static string Estimated_Arc_Fault_Current_amps {
            get {
                return ResourceManager.GetString("Estimated_Arc_Fault_Current_amps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Arc Flash Current.
        /// </summary>
        public static string Estimated_Arc_Flash_Current {
            get {
                return ResourceManager.GetString("Estimated_Arc_Flash_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceeds 40 cal/cm².
        /// </summary>
        public static string Exceeds_40 {
            get {
                return ResourceManager.GetString("Exceeds_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Equipment Trip Curves.
        /// </summary>
        public static string Find_Equipment_Trip_Curves {
            get {
                return ResourceManager.GetString("Find_Equipment_Trip_Curves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whenever possible, use manufacturer-provided device trip curves to determine the most precise 
        ///Arc Duration value. If the exact Arc Duration cannot be determined, enter a value of 2 seconds..
        /// </summary>
        public static string Find_Equipment_Trip_Curves_Header {
            get {
                return ResourceManager.GetString("Find_Equipment_Trip_Curves_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Safe Working Distance for Available PPE.
        /// </summary>
        public static string Find_Safe_Working_Distance {
            get {
                return ResourceManager.GetString("Find_Safe_Working_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash Protection Boundary (ft).
        /// </summary>
        public static string Flash_Protection_Boundary {
            get {
                return ResourceManager.GetString("Flash_Protection_Boundary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form contains error(s).
        /// </summary>
        public static string Form_Contains_Error {
            get {
                return ResourceManager.GetString("Form_Contains_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ft..
        /// </summary>
        public static string Ft {
            get {
                return ResourceManager.GetString("Ft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General_Heading {
            get {
                return ResourceManager.GetString("General_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grounding.
        /// </summary>
        public static string Grounding {
            get {
                return ResourceManager.GetString("Grounding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grounding Method.
        /// </summary>
        public static string Grounding_Method {
            get {
                return ResourceManager.GetString("Grounding_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select whether equipment voltage is supplied from a cable or bus only..
        /// </summary>
        public static string Has_Cable_Tooltip_Message {
            get {
                return ResourceManager.GetString("Has_Cable_Tooltip_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select whether an upstream transformer is present..
        /// </summary>
        public static string Has_Transformer_Tooltip_Message {
            get {
                return ResourceManager.GetString("Has_Transformer_Tooltip_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAZARD/RISK CATEGORY.
        /// </summary>
        public static string Hazard_Risk_Category {
            get {
                return ResourceManager.GetString("Hazard_Risk_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - .
        /// </summary>
        public static string Hyphen {
            get {
                return ResourceManager.GetString("Hyphen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Box.
        /// </summary>
        public static string In_Box {
            get {
                return ResourceManager.GetString("In_Box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select whether arc potential is in open air or in an enclosure..
        /// </summary>
        public static string In_Box_Tooltip_Message {
            get {
                return ResourceManager.GetString("In_Box_Tooltip_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Cabinet.
        /// </summary>
        public static string In_Cabinet {
            get {
                return ResourceManager.GetString("In_Cabinet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  inches.
        /// </summary>
        public static string Inches {
            get {
                return ResourceManager.GetString("Inches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} inches (non-standard).
        /// </summary>
        public static string InchesNonStandard {
            get {
                return ResourceManager.GetString("InchesNonStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} inches (standard).
        /// </summary>
        public static string InchesStandard {
            get {
                return ResourceManager.GetString("InchesStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INCIDENT ENERGY.
        /// </summary>
        public static string Incident_Energy {
            get {
                return ResourceManager.GetString("Incident_Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incident Energy 18&quot; (cal/cm²).
        /// </summary>
        public static string Incident_Energy_18 {
            get {
                return ResourceManager.GetString("Incident_Energy_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incident Energy 24&quot; (cal/cm²).
        /// </summary>
        public static string Incident_Energy_24 {
            get {
                return ResourceManager.GetString("Incident_Energy_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incident Energy 36&apos;&apos; (cal/cm²).
        /// </summary>
        public static string Incident_Energy_36 {
            get {
                return ResourceManager.GetString("Incident_Energy_36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (cal/cm²).
        /// </summary>
        public static string Incident_Energy_Measure {
            get {
                return ResourceManager.GetString("Incident_Energy_Measure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INCIDENT ENERGY PARAMETERS.
        /// </summary>
        public static string INCIDENT_ENERGY_PARAMETERS {
            get {
                return ResourceManager.GetString("INCIDENT_ENERGY_PARAMETERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incident Engery at Less Than 50 volts.
        /// </summary>
        public static string Incident_Engery_At_Less_Than_50_Volts {
            get {
                return ResourceManager.GetString("Incident_Engery_At_Less_Than_50_Volts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instantaneous (li).
        /// </summary>
        public static string Instantaneous {
            get {
                return ResourceManager.GetString("Instantaneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instantaneous (li) Setting.
        /// </summary>
        public static string Instantaneous_Setting {
            get {
                return ResourceManager.GetString("Instantaneous_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSULATING GLOVES CLASS.
        /// </summary>
        public static string Insulating_Gloves_Class {
            get {
                return ResourceManager.GetString("Insulating_Gloves_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  kcmil/AWG.
        /// </summary>
        public static string kcmil_Per_AWG {
            get {
                return ResourceManager.GetString("kcmil_Per_AWG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  KVA.
        /// </summary>
        public static string KVA {
            get {
                return ResourceManager.GetString("KVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;= 1.2  cal/cm².
        /// </summary>
        public static string LessThanEqualToOnePointTwo {
            get {
                return ResourceManager.GetString("LessThanEqualToOnePointTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: XYZ Facility-Dallas,TX.
        /// </summary>
        public static string Location_Example {
            get {
                return ResourceManager.GetString("Location_Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facility and specific equipment where the arc flash levels are being calculated..
        /// </summary>
        public static string Location_Tooltip_Message {
            get {
                return ResourceManager.GetString("Location_Tooltip_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Time Delay (tr).
        /// </summary>
        public static string Long_Time_Delay {
            get {
                return ResourceManager.GetString("Long_Time_Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Time Delay (tr) Setting.
        /// </summary>
        public static string Long_Time_Delay_Setting {
            get {
                return ResourceManager.GetString("Long_Time_Delay_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Time Pickup (lr).
        /// </summary>
        public static string Long_Time_Pickup {
            get {
                return ResourceManager.GetString("Long_Time_Pickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Time Pickup (lr) Setting.
        /// </summary>
        public static string Long_Time_Pickup_Setting {
            get {
                return ResourceManager.GetString("Long_Time_Pickup_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        public static string Manufacturer {
            get {
                return ResourceManager.GetString("Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Available.
        /// </summary>
        public static string Maximum_Available {
            get {
                return ResourceManager.GetString("Maximum_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Available Short.
        /// </summary>
        public static string Maximum_Available_Short {
            get {
                return ResourceManager.GetString("Maximum_Available_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Available Short Circuit (amps).
        /// </summary>
        public static string Maximum_Available_Short_Circuit {
            get {
                return ResourceManager.GetString("Maximum_Available_Short_Circuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Incident Energy.
        /// </summary>
        public static string Maximum_Incident_Energy {
            get {
                return ResourceManager.GetString("Maximum_Incident_Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Short Circuit Available.
        /// </summary>
        public static string Maximum_Short_Circuit_Available {
            get {
                return ResourceManager.GetString("Maximum_Short_Circuit_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short-Circuit Amps per battery manufacturer technical specification.
        ///If Manufacturer does not publish &quot;Maximum Available Short Circuit&quot; level but &quot;1 minute current to 1.75 volts per cell (VPC)&quot; is published, then the Maximum Short Circuit can be conservatively calculated by multiplying the &quot;1 minute amp to 1.75 VPC&quot; value by 10..
        /// </summary>
        public static string Maximum_Short_Circuit_Available_Tooltip_Message {
            get {
                return ResourceManager.GetString("Maximum_Short_Circuit_Available_Tooltip_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Working Distance.
        /// </summary>
        public static string Minimum_Working_Distance {
            get {
                return ResourceManager.GetString("Minimum_Working_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40 cal/cm².
        /// </summary>
        public static string Minimum_Working_Distance_40Cal {
            get {
                return ResourceManager.GetString("Minimum_Working_Distance_40Cal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 cal/cm².
        /// </summary>
        public static string Minimum_Working_Distance_8Cal {
            get {
                return ResourceManager.GetString("Minimum_Working_Distance_8Cal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.2 cal/cm².
        /// </summary>
        public static string Minimum_Working_Distance_OnePointTwoCal {
            get {
                return ResourceManager.GetString("Minimum_Working_Distance_OnePointTwoCal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple of Sensor Rating.
        /// </summary>
        public static string Multiple_Of_Sensor_Rating {
            get {
                return ResourceManager.GetString("Multiple_Of_Sensor_Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Calculation Based on Working Distance at 150 inches.
        /// </summary>
        public static string New_Calculation_for_150_inches {
            get {
                return ResourceManager.GetString("New_Calculation_for_150_inches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Calculation Based on Working Distance at 32 inches.
        /// </summary>
        public static string New_Calculation_for_32_inches {
            get {
                return ResourceManager.GetString("New_Calculation_for_32_inches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Calculation Based on Working Distance at 64 inches.
        /// </summary>
        public static string New_Calculation_for_64_inches {
            get {
                return ResourceManager.GetString("New_Calculation_for_64_inches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Cable - Bus Only.
        /// </summary>
        public static string No_Cable {
            get {
                return ResourceManager.GetString("No_Cable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select whether equipment voltage is supplied from a cable or bus only..
        /// </summary>
        public static string No_Cable_Tooltip_Message {
            get {
                return ResourceManager.GetString("No_Cable_Tooltip_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Transformer.
        /// </summary>
        public static string No_Transformer {
            get {
                return ResourceManager.GetString("No_Transformer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select whether an upstream transformer is present..
        /// </summary>
        public static string No_Transformer_Tooltip_Message {
            get {
                return ResourceManager.GetString("No_Transformer_Tooltip_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: 240.
        /// </summary>
        public static string Nominal_Voltage_Example {
            get {
                return ResourceManager.GetString("Nominal_Voltage_Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus voltage of the equipment to be worked on OR - if transformer is present, transformer secondary voltage.
        ///
        ///Valid Range: 30-36000.
        /// </summary>
        public static string Nominal_Voltage_Tooltip_Message_Default {
            get {
                return ResourceManager.GetString("Nominal_Voltage_Tooltip_Message_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus voltage of the equipment to be worked on OR - if transformer is present, transformer secondary voltage.
        ///
        ///Valid Range for Equipment Type: 30-1000.
        /// </summary>
        public static string Nominal_Voltage_Tooltip_Message_Low_Voltage {
            get {
                return ResourceManager.GetString("Nominal_Voltage_Tooltip_Message_Low_Voltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus voltage of the equipment to be worked on OR - if transformer is present, transformer secondary voltage.
        ///
        ///Valid Range for Equipment Type: 1001-36000.
        /// </summary>
        public static string Nominal_Voltage_Tooltip_Message_Medium_Voltage {
            get {
                return ResourceManager.GetString("Nominal_Voltage_Tooltip_Message_Medium_Voltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominal Working Voltage (volts).
        /// </summary>
        public static string Nominal_Working_Voltage {
            get {
                return ResourceManager.GetString("Nominal_Working_Voltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string Number_2 {
            get {
                return ResourceManager.GetString("Number_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string Number_3 {
            get {
                return ResourceManager.GetString("Number_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string Number_4 {
            get {
                return ResourceManager.GetString("Number_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Air.
        /// </summary>
        public static string Open_Air {
            get {
                return ResourceManager.GetString("Open_Air", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select whether arc potential is in open air or in an enclosure..
        /// </summary>
        public static string Open_Air_Tooltip_Message {
            get {
                return ResourceManager.GetString("Open_Air_Tooltip_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Calculation Based on Standard Working Distance at {0:N0} inches.
        /// </summary>
        public static string OriginalCalculationBasedOnStandardWorkingDistance {
            get {
                return ResourceManager.GetString("OriginalCalculationBasedOnStandardWorkingDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARAMETER CONFIRMATION.
        /// </summary>
        public static string PARAMETER_CONFIRMATION {
            get {
                return ResourceManager.GetString("PARAMETER_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform New Arc Flash Calculation?.
        /// </summary>
        public static string Perform_New_Arc_Flash_Calculation {
            get {
                return ResourceManager.GetString("Perform_New_Arc_Flash_Calculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personnel.
        /// </summary>
        public static string Personnel {
            get {
                return ResourceManager.GetString("Personnel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: Jane Smith.
        /// </summary>
        public static string Personnel_Example {
            get {
                return ResourceManager.GetString("Personnel_Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All personnel who should be informed of the available arc flash levels..
        /// </summary>
        public static string Personnel_Tooltip_Message {
            get {
                return ResourceManager.GetString("Personnel_Tooltip_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point of work.
        /// </summary>
        public static string Point_Of_Work {
            get {
                return ResourceManager.GetString("Point_Of_Work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potential Arc Location.
        /// </summary>
        public static string Potential_Arc_Location {
            get {
                return ResourceManager.GetString("Potential_Arc_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPE LEVEL REQUIRED.
        /// </summary>
        public static string PPE_LEVEL_REQUIRED {
            get {
                return ResourceManager.GetString("PPE_LEVEL_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPE Rating: Hazard/Risk Category.
        /// </summary>
        public static string PPE_Rating_Hazard_Risk_Category {
            get {
                return ResourceManager.GetString("PPE_Rating_Hazard_Risk_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Voltage (volts).
        /// </summary>
        public static string Primary_Voltage {
            get {
                return ResourceManager.GetString("Primary_Voltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: 2000.
        /// </summary>
        public static string Primary_Voltage_Example {
            get {
                return ResourceManager.GetString("Primary_Voltage_Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltage at the transformer primary Valid range: 208 - 138000.
        /// </summary>
        public static string Primary_Voltage_Tooltip_Message {
            get {
                return ResourceManager.GetString("Primary_Voltage_Tooltip_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}V Primary.
        /// </summary>
        public static string PrimaryVoltage {
            get {
                return ResourceManager.GetString("PrimaryVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protective Clothing Requirements.
        /// </summary>
        public static string Protective_Clothing_Requirements {
            get {
                return ResourceManager.GetString("Protective_Clothing_Requirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Fields.
        /// </summary>
        public static string Required_Fields {
            get {
                return ResourceManager.GetString("Required_Fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Minimum Arc Rating of PPE (cal/cm²).
        /// </summary>
        public static string Required_Minimum_Arc_Rating {
            get {
                return ResourceManager.GetString("Required_Minimum_Arc_Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Minimum Arc Rating of PPE (cal/cm²): {0}.
        /// </summary>
        public static string Required_Minimum_Arc_Rating_Pdf {
            get {
                return ResourceManager.GetString("Required_Minimum_Arc_Rating_Pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  sec..
        /// </summary>
        public static string Sec {
            get {
                return ResourceManager.GetString("Sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}V Secondary.
        /// </summary>
        public static string SecondaryVoltage {
            get {
                return ResourceManager.GetString("SecondaryVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Rating.
        /// </summary>
        public static string Sensor_Rating {
            get {
                return ResourceManager.GetString("Sensor_Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: 4000.
        /// </summary>
        public static string Sensor_Rating_Example {
            get {
                return ResourceManager.GetString("Sensor_Rating_Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If using a Square D time current curve to determine device opening time, enter the sensor rating based on curve data..
        /// </summary>
        public static string Sensor_Rating_Tooltip_Message {
            get {
                return ResourceManager.GetString("Sensor_Rating_Tooltip_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Circuit (amps).
        /// </summary>
        public static string Short_Circuit_Amps {
            get {
                return ResourceManager.GetString("Short_Circuit_Amps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Time Delay (tsd).
        /// </summary>
        public static string Short_Time_Delay {
            get {
                return ResourceManager.GetString("Short_Time_Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Time Delay (tsd) Setting.
        /// </summary>
        public static string Short_Time_Delay_Setting {
            get {
                return ResourceManager.GetString("Short_Time_Delay_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Time Pickup (lsd).
        /// </summary>
        public static string Short_Time_Pickup {
            get {
                return ResourceManager.GetString("Short_Time_Pickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Time Pickup (lsd) Setting.
        /// </summary>
        public static string Short_Time_Pickup_Setting {
            get {
                return ResourceManager.GetString("Short_Time_Pickup_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the system grounding method..
        /// </summary>
        public static string Solid_Grounding_Tooltip_Message {
            get {
                return ResourceManager.GetString("Solid_Grounding_Tooltip_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solidly Grounded.
        /// </summary>
        public static string Solidly_Grounded {
            get {
                return ResourceManager.GetString("Solidly_Grounded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Fault Current.
        /// </summary>
        public static string Source_Fault_Current {
            get {
                return ResourceManager.GetString("Source_Fault_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Fault Current (amps).
        /// </summary>
        public static string Source_Fault_Current_amps {
            get {
                return ResourceManager.GetString("Source_Fault_Current_amps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: 15000.
        /// </summary>
        public static string Source_Fault_Current_Example {
            get {
                return ResourceManager.GetString("Source_Fault_Current_Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The available short-circuit current supplied by the utility or on-site generator.  If not known use 99999 at the primary of the serving transformer..
        /// </summary>
        public static string Source_Fault_Current_Tooltip_Message {
            get {
                return ResourceManager.GetString("Source_Fault_Current_Tooltip_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Voltage.
        /// </summary>
        public static string Source_Voltage {
            get {
                return ResourceManager.GetString("Source_Voltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}A.
        /// </summary>
        public static string SourceFaultCurrent {
            get {
                return ResourceManager.GetString("SourceFaultCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Working Distance.
        /// </summary>
        public static string Standard_Working_Distance {
            get {
                return ResourceManager.GetString("Standard_Working_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Working Distances.
        /// </summary>
        public static string Standard_Working_Distances {
            get {
                return ResourceManager.GetString("Standard_Working_Distances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        public static string Star {
            get {
                return ResourceManager.GetString("Star", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arc Flash Calculator.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transformer?.
        /// </summary>
        public static string Transformer {
            get {
                return ResourceManager.GetString("Transformer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transformer.
        /// </summary>
        public static string Transformer_Heading {
            get {
                return ResourceManager.GetString("Transformer_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transformer Impedence (%Z).
        /// </summary>
        public static string Transformer_Impedence {
            get {
                return ResourceManager.GetString("Transformer_Impedence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: 5.75.
        /// </summary>
        public static string Transformer_Impedence_Example {
            get {
                return ResourceManager.GetString("Transformer_Impedence_Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transformer KVA.
        /// </summary>
        public static string Transformer_KVA {
            get {
                return ResourceManager.GetString("Transformer_KVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: 500.
        /// </summary>
        public static string Transformer_KVA_Example {
            get {
                return ResourceManager.GetString("Transformer_KVA_Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transformer %Z.
        /// </summary>
        public static string Transformer_Z {
            get {
                return ResourceManager.GetString("Transformer_Z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} %Z.
        /// </summary>
        public static string TransformerImpedence {
            get {
                return ResourceManager.GetString("TransformerImpedence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} KVA.
        /// </summary>
        public static string TransformerKVA {
            get {
                return ResourceManager.GetString("TransformerKVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial Version:.
        /// </summary>
        public static string Trial_Version {
            get {
                return ResourceManager.GetString("Trial_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Unit Type.
        /// </summary>
        public static string Trip_Unit_Type {
            get {
                return ResourceManager.GetString("Trip_Unit_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungrounded (or Resistance Grounded).
        /// </summary>
        public static string Ungrounded {
            get {
                return ResourceManager.GetString("Ungrounded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the system grounding method..
        /// </summary>
        public static string UnGrounded_Tooltip_Message {
            get {
                return ResourceManager.GetString("UnGrounded_Tooltip_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units of Measure.
        /// </summary>
        public static string Units_of_Measure {
            get {
                return ResourceManager.GetString("Units_of_Measure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upstream Transformer?.
        /// </summary>
        public static string Upstream_Transformer {
            get {
                return ResourceManager.GetString("Upstream_Transformer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upstream XFMR.
        /// </summary>
        public static string Upstream_XFR {
            get {
                return ResourceManager.GetString("Upstream_XFR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use For New Calculation.
        /// </summary>
        public static string UseForNewCalculation {
            get {
                return ResourceManager.GetString("UseForNewCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  V.
        /// </summary>
        public static string V {
            get {
                return ResourceManager.GetString("V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltage Conductor.
        /// </summary>
        public static string Voltage_Conductor {
            get {
                return ResourceManager.GetString("Voltage_Conductor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VoltageFromTransformer?.
        /// </summary>
        public static string Voltage_From_Transformer {
            get {
                return ResourceManager.GetString("Voltage_From_Transformer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum string voltage, or partial string voltage if all batteries are not connected..
        /// </summary>
        public static string Voltage_Of_Battery_Tooltip_Message {
            get {
                return ResourceManager.GetString("Voltage_Of_Battery_Tooltip_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltage Shock Hazard when Cover is Open: {0}V AC.
        /// </summary>
        public static string Voltage_Shock_Hazard_AC {
            get {
                return ResourceManager.GetString("Voltage_Shock_Hazard_AC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltage Shock Hazard when Cover is Open: {0}V DC.
        /// </summary>
        public static string Voltage_Shock_Hazard_DC {
            get {
                return ResourceManager.GetString("Voltage_Shock_Hazard_DC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltage Type.
        /// </summary>
        public static string Voltage_Type {
            get {
                return ResourceManager.GetString("Voltage_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AC.
        /// </summary>
        public static string Voltage_Type_AC {
            get {
                return ResourceManager.GetString("Voltage_Type_AC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DC.
        /// </summary>
        public static string Voltage_Type_DC {
            get {
                return ResourceManager.GetString("Voltage_Type_DC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Conditions:.
        /// </summary>
        public static string Working_Conditions_Heading {
            get {
                return ResourceManager.GetString("Working_Conditions_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        public static string X {
            get {
                return ResourceManager.GetString("X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transformer percent impedance (%Z or %X). Typcially found on transformer nameplate.Valid range: 1.00 - 15.00.
        /// </summary>
        public static string Xfmr_Impedance_Tooltip_Message {
            get {
                return ResourceManager.GetString("Xfmr_Impedance_Tooltip_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transformer kVA is require to determine available fault current on secondary of transformer.Data may be found on transformer nameplate..
        /// </summary>
        public static string Xfmr_KVA_Tooltip_Message {
            get {
                return ResourceManager.GetString("Xfmr_KVA_Tooltip_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  %Z.
        /// </summary>
        public static string Z {
            get {
                return ResourceManager.GetString("Z", resourceCulture);
            }
        }
    }
}
